/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        

        
/**
 * resources/ui/prefab/gm/Item_GmProCmd.lh
 */
export class Runtime_Item_GmProCmdBase extends Laya.GWidget {
    public lbInput!: Laya.GTextInput;
    public lbType!: Laya.GTextField;
}
        
