/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        
import { ButtonBase } from "../Component/ButtonBase";
        
/**
 * resources/ui/prefab/gm/Vw_Gm.lh
 */
export class Runtime_Vw_GmBase extends Laya.GWidget {
    public tabList!: Laya.GList;
    public lbSearch!: Laya.GTextInput;
    public btnSearch!: ButtonBase;
    public list!: Laya.GList;
    public linkGp!: Laya.GWidget;
    public linkList!: Laya.GList;
}
        
