/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        
import { ButtonBase } from "../Component/ButtonBase";
        
/**
 * resources/ui/prefab/gm/Vw_GmBtn.lh
 */
export class Runtime_Vw_GmBtnBase extends Laya.GWidget {
    public btn!: ButtonBase;
    public btnGp!: Laya.GBox;
    public btnGm!: ButtonBase;
    public btnProtocol!: ButtonBase;
    public btnLock!: ButtonBase;
}
        
