/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        
import { ButtonBase } from "../Component/ButtonBase";
        
/**
 * resources/ui/prefab/gm/Item_GmProGp.lh
 */
export class Runtime_Item_GmProGpBase extends Laya.GWidget {
    public lbTitle!: Laya.GTextField;
    public lbEnd!: Laya.GTextField;
    public btnAdd!: ButtonBase;
    public btnDel!: ButtonBase;
}
        
