/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/gm/Item_Gm.lh
 */
export class Runtime_Item_GmBase extends Laya.GWidget {
    public bg1!: Laya.GImage;
    public bg2!: Laya.GImage;
    public lbTitle1!: Laya.GTextField;
    public lbTitle2!: Laya.GTextField;
    public lbInput1!: Laya.GTextInput;
    public lbInput2!: Laya.GTextInput;
    public btn!: ButtonBase;
}

