/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        
import { ButtonBase } from "../Component/ButtonBase";
import Runtime_Item_GmProGp from "./Runtime_Item_GmProGp";
import Runtime_Item_GmProCmd from "./Runtime_Item_GmProCmd";
        
/**
 * resources/ui/prefab/gm/Vw_GmProtocol.lh
 */
export class Runtime_Vw_GmProtocolBase extends Laya.GWidget {
    public lbDes!: Laya.GTextField;
    public lbCmd!: Laya.GTextInput;
    public btnAdd!: ButtonBase;
    public btnClear!: ButtonBase;
    public btnSend!: ButtonBase;
    public lbCount!: Laya.GTextInput;
    public container!: Laya.GPanel;
    public itemGp!: Runtime_Item_GmProGp;
    public search!: Laya.GWidget;
    public searchList!: Laya.GList;
    public proCmd!: Runtime_Item_GmProCmd;
}
        
