/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/shop/Item_Shop1.lh
 */
export class Item_Shop1Base extends Laya.GWidget {
    public list!: Laya.GList;
}

