/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/shop/Item_Shop_Grid2.lh
 */
export class Item_Shop_GridBase extends Laya.GButton {
    public img!: Laya.GImage;
    public btn!: Laya.GButton;
    public imgAd!: Laya.GImage;
    public txtBtn!: Laya.GTextField;
    public lbName!: Laya.GTextField;
}

