/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/shop/Item_Shop2.lh
 */
export class Item_Shop2Base extends Laya.GWidget {
    public imgTitle!: Laya.GImage;
    public title!: Laya.GTextField;
    public list!: Laya.GList;
}

