/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/shop/Item_Shop3.lh
 */
export class Item_Shop3Base extends Laya.GWidget {
    public title!: Laya.GTextField;
    public list!: Laya.GList;
}

