/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/shop/Vw_Shop.lh
 */
export class Runtime_Vw_ShopBase extends Laya.GWidget {
    public imgBlack!: Laya.GImage;
    public imgTop!: Laya.GImage;
    public panel!: Laya.GPanel;
    public topGp!: Laya.GWidget;
    public imgLimitless!: Laya.GImage;
    public btnStamina!: ButtonBase;
    public btnGold!: ButtonBase;
    public btnClose!: ButtonBase;
    public lbStaminaTime!: Laya.GTextField;
    public lbStamina!: Laya.GTextField;
    public lbGold!: Laya.GTextField;
}

