/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/shop/Vw_AdCard.lh
 */
export class Runtime_Vw_AdCardBase extends Laya.GWidget {
    public imgIcon!: Laya.GImage;
    public btnClose!: Laya.GButton;
    public btn!: Laya.GButton;
    public imgAd!: Laya.GImage;
    public txtBtn!: Laya.GTextField;
    public txtTitle!: Laya.GTextField;
    public txt1!: Laya.GTextField;
    public txt2!: Laya.GTextField;
    public txt3!: Laya.GTextField;
}

