/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        
import { ButtonBase } from "../Component/ButtonBase";
        
/**
 * resources/ui/prefab/login/Vw_Login.lh
 */
export class Runtime_Vw_LoginBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public logo!: Laya.GImage;
    public loading!: Laya.GWidget;
    public pb!: Laya.GProgressBar;
    public lbDes!: Laya.GTextField;
    public reloadBtn!: ButtonBase;
    public input!: Laya.GWidget;
    public servBtn!: Laya.GButton;
    public lbId!: Laya.GTextInput;
    public enterBtn!: ButtonBase;
}
        
