/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/login/Vw_ServerList.lh
 */
export class Runtime_Vw_ServerListBase extends Laya.GWidget {
    public list!: Laya.GList;
}

