/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/arena/Item_Arena_Rank.lh
 */
export class Item_Arena_RankBase extends Laya.GWidget {
    public imgCur!: Laya.GImage;
    public imgRank!: Laya.GImage;
    public imgHead!: Laya.GImage;
    public btnBox!: ButtonBase;
    public lbRank!: Laya.GTextField;
    public lbName!: Laya.GTextField;
    public lbItemCnt!: Laya.GTextField;
    public lbSum!: Laya.GTextField;
}

