/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/arena/Item_Arena_Add.lh
 */
export class Item_Arena_AddBase extends Laya.GWidget {
    public imgSelect!: Laya.GImage;
    public lbAdd!: Laya.GTextField;
}

