/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/arena/Vw_Arena_Again.lh
 */
export class Runtime_Vw_Arena_AgainBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public lbDes!: Laya.GTextField;
    public lbTitle!: Laya.GTextField;
    public btnOK!: ButtonBase;
    public btnClose!: ButtonBase;
}

