/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/arena/Vw_Arena_Reward.lh
 */
export class Runtime_Vw_Arena_RewardBase extends Laya.GWidget {
    public imgItem!: Laya.GImage;
    public lbTitle!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
    public lbDes1!: Laya.GTextField;
    public lbCnt!: Laya.GTextField;
    public lbDes2!: Laya.GTextField;
}

