/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/arena/Vw_Arena_Guilde.lh
 */
export class Runtime_Vw_Arena_GuildeBase extends Laya.GWidget {
    public imgTitle!: Laya.GImage;
    public img1!: Laya.GImage;
    public img2!: Laya.GImage;
    public img3!: Laya.GImage;
    public img4!: Laya.GImage;
    public img5!: Laya.GImage;
    public lbTitle!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
}

