/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/arena/Vw_Arena.lh
 */
export class Runtime_Vw_ArenaBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public rankList!: Laya.GList;
    public imgBottom!: Laya.GImage;
    public contentEnd!: Laya.GWidget;
    public rankBox!: Laya.GWidget;
    public lbDes1!: Laya.GTextField;
    public lbRank!: Laya.GTextField;
    public imgLight!: Laya.GImage;
    public btnBox!: Laya.GButton;
    public lbDes2!: Laya.GTextField;
    public lbDes3!: Laya.GTextField;
    public lbItemCnt!: Laya.GTextField;
    public contentCur!: Laya.GWidget;
    public addList!: Laya.GList;
    public lbDes!: Laya.GTextField;
    public lbTime!: Laya.GTextField;
    public btnDetail!: ButtonBase;
    public btnGet!: ButtonBase;
    public btnClose!: Laya.GButton;
    public lbTitle!: Laya.GTextField;
}

