/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../../Component/ButtonBase";


/**
 * resources/ui/prefab/stage/component/Btn_StageSkill.lh
 */
export class Runtime_Btn_StageSkillBase extends ButtonBase {
    public countBg!: Laya.GImage;
    public imgAdd!: Laya.GImage;
    public lbCount!: Laya.GTextField;
}

