/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/stage/component/Group_StageLev.lh
 */
export class Runtime_Group_StageLevBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public item0!: Laya.GButton;
    public item1!: Laya.GButton;
    public item2!: Laya.GButton;
    public item3!: Laya.GButton;
    public item4!: Laya.GButton;
    public item5!: Laya.GButton;
    public item6!: Laya.GButton;
    public item7!: Laya.GButton;
    public item8!: Laya.GButton;
    public item9!: Laya.GButton;
}

