/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/stage/component/Stage_HurtFly.lh
 */
export class Runtime_Stage_HurtFlyBase extends Laya.GWidget {
    public lbHurt!: Laya.GTextField;
}

