/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/stage/component/Item_StageTarget.lh
 */
export class Runtime_Item_StageTargetBase extends Laya.GWidget {
    public imgIcon!: Laya.GImage;
    public lbCount!: Laya.GTextField;
    public imgMask0!: Laya.GImage;
    public imgMask1!: Laya.GImage;
}

