/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
        
import { ButtonBase } from "../../Component/ButtonBase";
        
/**
 * resources/ui/prefab/stage/component/Btn_RewardAd.lh
 */
export class Runtime_Btn_RewardAdBase extends ButtonBase {
    public lbMul!: Laya.GTextField;
}
        
