/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/stage/component/Stage_PlayerDir.lh
 */
export class Runtime_Stage_PlayerDirBase extends Laya.GWidget {
    public imgBg!: Laya.GImage;
    public imgIcon!: Laya.GImage;
    public bg!: Laya.GImage;
    public lb!: Laya.GTextField;
}

