/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/role/Item_Role.lh
 */
export class Item_RoleBase extends Laya.GButton {
    public imgHead!: Laya.GImage;
    public imgCur!: Laya.GImage;
    public imgLock!: Laya.GImage;
}

