/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/role/Vw_Role_Name_Sure.lh
 */
export class Runtime_Vw_Role_Name_SureBase extends Laya.GWidget {
    public lbTitle!: Laya.GTextField;
    public lb1!: Laya.GTextField;
    public lbName!: Laya.GTextField;
    public btnClose!: Laya.GButton;
    public btn0!: ButtonBase;
    public btn1!: ButtonBase;
}

