/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/role/Vw_Error.lh
 */
export class Runtime_Vw_ErrorBase extends Laya.GWidget {
    public lbTitle!: Laya.GTextField;
    public lbMs!: Laya.GTextField;
    public img!: Laya.GImage;
    public btnClose!: Laya.GButton;
    public btn!: ButtonBase;
}

