/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/role/Vw_Role_Name.lh
 */
export class Runtime_Vw_Role_NameBase extends Laya.GWidget {
    public lbTitle!: Laya.GTextField;
    public input!: Laya.GTextInput;
    public btnClose!: Laya.GButton;
    public btn!: ButtonBase;
}

