/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/role/Vw_Role.lh
 */
export class Runtime_Vw_RoleBase extends Laya.GWidget {
    public imgHead!: Laya.GLoader;
    public list!: Laya.GList;
    public btn!: ButtonBase;
    public btnName!: Laya.GButton;
    public lbName!: Laya.GTextField;
    public btnClose!: Laya.GButton;
    public lbTitle!: Laya.GTextField;
}

