/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/setting/Vw_Setting.lh
 */
export class Runtime_Vw_SettingBase extends Laya.GWidget {
    public musicSd!: Laya.GSlider;
    public soundSd!: Laya.GSlider;
    public btnClose!: ButtonBase;
    public lbTitle!: Laya.GTextField;
    public lb0!: Laya.GTextField;
    public lb1!: Laya.GTextField;
    public lb2!: Laya.GTextField;
    public lb3!: Laya.GTextField;
    public btnShake!: Laya.GButton;
    public lbShake0!: Laya.GTextField;
    public lbShake1!: Laya.GTextField;
    public btn0!: ButtonBase;
    public btn1!: ButtonBase;
    public btn2!: ButtonBase;
    public btn3!: ButtonBase;
    public btnStart!: ButtonBase;
    public btnHome!: ButtonBase;
    public lbVersion!: Laya.GTextField;
    public btnBox!: Laya.GComboBox;
}

