/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/component/Btn_BlueCost.lh
 */
export class ButtonBaseBase extends Laya.GButton {
}

