/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/main/Vw_GuideLayer.lh
 */
export class Runtime_Vw_GuideLayerBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public bgDesc!: Laya.GImage;
    public txtDesc!: Laya.GTextField;
}

