/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";
import { Runtime_Item_Arena } from "./Comp/Runtime_Item_Arena";
import { Runtime_Item_FireTrial } from "./Comp/Runtime_Item_FireTrial";
import { Runtime_Item_AdCard } from "./Comp/Runtime_Item_AdCard";
import { Runtime_Item_WarOrder } from "./Comp/Runtime_Item_WarOrder";

/**
 * resources/ui/prefab/main/Vw_Main.lh
 */
export class Runtime_Vw_MainBase extends Laya.GWidget {
    public imgBtm!: Laya.GImage;
    public topGp!: Laya.GWidget;
    public imgHead!: Laya.GImage;
    public btnSeting!: ButtonBase;
    public imgGold!: Laya.GImage;
    public imgLimitless!: Laya.GImage;
    public btnStamina!: ButtonBase;
    public btnGold!: ButtonBase;
    public lbStaminaTime!: Laya.GTextField;
    public lbStamina!: Laya.GTextField;
    public lbGold!: Laya.GTextField;
    public btnRoot!: Laya.GWidget;
    public btnArena!: Runtime_Item_Arena;
    public btnFireTrial!: Runtime_Item_FireTrial;
    public btnAdCard!: Runtime_Item_AdCard;
    public btnWarOrder!: Runtime_Item_WarOrder;
    public btmGp!: Laya.GWidget;
    public btnShop!: ButtonBase;
    public btnStage!: ButtonBase;
}

