/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/main/Vw_HeroAttribute.lh
 */
export class Runtime_Vw_HeroAttributeBase extends Laya.GWidget {
    public compGold!: Laya.GLabel;
    public btnClose!: ButtonBase;
    public list!: Laya.GList;
}

