/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";
import { Runtime_Btn_BuyStamina } from "./Comp/Runtime_Btn_BuyStamina";

/**
 * resources/ui/prefab/main/Vw_BuyStamina.lh
 */
export class Runtime_Vw_BuyStaminaBase extends Laya.GWidget {
    public btnClose!: ButtonBase;
    public btnAd!: Laya.GButton;
    public btnBuy!: Runtime_Btn_BuyStamina;
    public lbTitle!: Laya.GTextField;
    public lbNum!: Laya.GTextField;
    public lbTimeTitle!: Laya.GTextField;
    public lbTime!: Laya.GTextField;
}

