DataSDK_Inside_Http_Path=https://columbus.3k.com
DataSDK_Domestic_URL_V2=https://columbus.3k.com/a.gif
DataSDK_Domestic_OPS_V2=https://columbus.3k.com/ops.gif
DataSDK_Outside_Http_Path=https://columbus.kkkvenus.com/ep.gif|https://columbus.kkkzeus.com/ep.gif|https://columbus.kkkathena.com/ep.gif
isAutoFillUrlIndex=false
