#融合自检开关
FUSE_SELF_CHECK=false
#3k 融合拿包id
3KWAN_PackageID=36906

#3k 融合分发id
3KWAN_ChanleId=36906
#融合配置id
3KWAN_DeployID=3441
#游戏id
3KWAN_GAMEID=2052
#平台id
3KWAN_Platform_ChanleId=0

#是否显示平台闪屏
3KWAN_HasLogo=false