/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/common/Item_Reward_Grid.lh
 */
export class Item_GridBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public lbCnt!: Laya.GTextField;
}

