/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/common/Vw_RewardAlert.lh
 */
export class Runtime_Vw_RewardAlertBase extends Laya.GWidget {
    public titleSpine!: Laya.GWidget;
    public list!: Laya.GList;
    public lbDes!: Laya.GTextField;
    public lbDes1!: Laya.GTextField;
    public lbDes2!: Laya.GTextField;
}

