/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/common/Vw_ItemDescTip.lh
 */
export class Runtime_Vw_ItemDescTipBase extends Laya.GWidget {
    public box!: Laya.GBox;
    public bg!: Laya.GImage;
    public imgJt!: Laya.GImage;
    public txtDesc!: Laya.GTextField;
}

