/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/common/Vw_RewardTip.lh
 */
export class Runtime_Vw_RewardTipBase extends Laya.GWidget {
    public content!: Laya.GWidget;
    public bg!: Laya.GImage;
    public img_1!: Laya.GImage;
    public list!: Laya.GList;
}

