/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";
import { Runtime_Btn_StageSkill } from "./Component/Runtime_Btn_StageSkill";

/**
 * resources/ui/prefab/stage/Vw_SceneStage.lh
 */
export class Runtime_Vw_SceneStageBase extends Laya.GWidget {
    public flyBase!: Laya.GWidget;
    public area!: Laya.GWidget;
    public topCenter!: Laya.GWidget;
    public stageNameBg!: Laya.GImage;
    public lbTime!: Laya.GTextField;
    public lbStage!: Laya.GTextField;
    public imgGold!: Laya.GImage;
    public btnGold!: ButtonBase;
    public lbGold!: Laya.GTextField;
    public startGp!: Laya.GWidget;
    public imgStart!: Laya.GImage;
    public btnSeting!: ButtonBase;
    public btmGp!: Laya.GWidget;
    public btnSkill0!: Runtime_Btn_StageSkill;
    public btnSkill1!: Runtime_Btn_StageSkill;
    public btnSkill2!: Runtime_Btn_StageSkill;
    public btnSkill3!: Runtime_Btn_StageSkill;
    public targetGp!: Laya.GWidget;
    public targetList!: Laya.GList;
    public lbTarget!: Laya.GTextField;
    public guideGp!: Laya.GWidget;
    public lbGuide!: Laya.GTextField;
    public moveEff!: Laya.GWidget;
    public lbCountDown!: Laya.GTextField;
}

