/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/stage/Vw_BuySkill.lh
 */
export class Runtime_Vw_BuySkillBase extends Laya.GWidget {
    public spineBase!: Laya.GWidget;
    public imgIcon!: Laya.GImage;
    public btnClose!: ButtonBase;
    public btn!: ButtonBase;
    public lbTitle!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
    public lbCount!: Laya.GTextField;
}

