/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Runtime_Group_StageLev } from "./Component/Runtime_Group_StageLev";
import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/stage/Vw_Stage.lh
 */
export class Runtime_Vw_StageBase extends Laya.GWidget {
    public groupBase!: Laya.GPanel;
    public group3!: Runtime_Group_StageLev;
    public group2!: Runtime_Group_StageLev;
    public group1!: Runtime_Group_StageLev;
    public group0!: Runtime_Group_StageLev;
    public btnAttr!: ButtonBase;
    public btnStart!: ButtonBase;
    public lbId!: Laya.GTextInput;
    public txt!: Laya.GTextField;
}

