/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/stage/Vw_Fail.lh
 */
export class Runtime_Vw_FailBase extends Laya.GWidget {
    public btnClose!: ButtonBase;
    public btnRelive!: ButtonBase;
    public btnExit!: ButtonBase;
    public lbTitle!: Laya.GTextField;
    public giftBase!: Laya.GPanel;
    public gift0!: Laya.GButton;
    public btnGift0!: Laya.GButton;
    public imgGitfAd0!: Laya.GImage;
    public lbGitf0!: Laya.GTextField;
    public gift1Base!: Laya.GWidget;
    public gift1!: Laya.GButton;
    public btnGift1!: Laya.GButton;
    public imgGitfAd1!: Laya.GImage;
    public lbGitf1!: Laya.GTextField;
    public normalBase!: Laya.GWidget;
    public imgIcon!: Laya.GImage;
    public lbStrength!: Laya.GTextField;
    public lbTime!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
    public arenaState!: Laya.GImage;
    public arenaBg0!: Laya.GImage;
    public arenaBg1!: Laya.GImage;
    public arenaBg2!: Laya.GImage;
    public arenaBg3!: Laya.GImage;
    public arenaBg4!: Laya.GImage;
    public lbArenaDes!: Laya.GTextField;
    public lbArena0!: Laya.GTextField;
    public lbArena1!: Laya.GTextField;
    public lbArena2!: Laya.GTextField;
    public lbArena3!: Laya.GTextField;
    public lbArena4!: Laya.GTextField;
    public fireState!: Laya.GImage;
    public lbFireDes!: Laya.GTextField;
}

