/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/stage/Vw_ExitStage.lh
 */
export class Runtime_Vw_ExitStageBase extends Laya.GWidget {
    public btnClose!: ButtonBase;
    public btn!: ButtonBase;
    public lbTitle!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
    public lbStrength!: Laya.GTextField;
    public imgIcon!: Laya.GImage;
    public fireState!: Laya.GImage;
    public arenaState!: Laya.GImage;
    public arenaBg0!: Laya.GImage;
    public arenaBg1!: Laya.GImage;
    public arenaBg2!: Laya.GImage;
    public arenaBg3!: Laya.GImage;
    public arenaBg4!: Laya.GImage;
    public lbDes1!: Laya.GTextField;
    public lbArena0!: Laya.GTextField;
    public lbArena1!: Laya.GTextField;
    public lbArena2!: Laya.GTextField;
    public lbArena3!: Laya.GTextField;
    public lbArena4!: Laya.GTextField;
}

