/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";
import { Runtime_Btn_RewardAd } from "./Component/Runtime_Btn_RewardAd";

/**
 * resources/ui/prefab/stage/Vw_Pass.lh
 */
export class Runtime_Vw_PassBase extends Laya.GWidget {
    public panelBase!: Laya.GWidget;
    public goldSpine!: Laya.GWidget;
    public btnNext!: ButtonBase;
    public btnAd!: Runtime_Btn_RewardAd;
    public lbTitle!: Laya.GTextField;
    public lbReward!: Laya.GTextField;
    public lbCount!: Laya.GTextField;
    public moneyBase!: Laya.GWidget;
    public imgGold!: Laya.GImage;
    public btnGold!: ButtonBase;
    public lbGold!: Laya.GTextField;
}

