/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/fireTrial/Item_FireTrial_Head.lh
 */
export class Item_FireTrial_HeadBase extends Laya.GWidget {
    public panel!: Laya.GPanel;
    public box!: Laya.GWidget;
    public spineBox!: Laya.GWidget;
}

