/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";
import { Item_FireTrial_Head } from "./Item_FireTrial_Head";

/**
 * resources/ui/prefab/fireTrial/Vw_FireTrial_Main.lh
 */
export class Runtime_Vw_FireTrial_MainBase extends Laya.GWidget {
    public bg!: Laya.GLoader;
    public planBox!: Laya.GWidget;
    public lbTime!: Laya.GTextField;
    public lbDes1!: Laya.GTextField;
    public lbDes2!: Laya.GTextField;
    public lbPlan!: Laya.GTextField;
    public lbHuman!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
    public content!: Laya.GWidget;
    public img7!: Laya.GImage;
    public img6!: Laya.GImage;
    public img5!: Laya.GImage;
    public img4!: Laya.GImage;
    public img3!: Laya.GImage;
    public img2!: Laya.GImage;
    public img1!: Laya.GImage;
    public img0!: Laya.GImage;
    public pos0!: Laya.GWidget;
    public pos1!: Laya.GWidget;
    public pos2!: Laya.GWidget;
    public pos3!: Laya.GWidget;
    public pos4!: Laya.GWidget;
    public pos5!: Laya.GWidget;
    public pos6!: Laya.GWidget;
    public pos7!: Laya.GWidget;
    public headBox!: Laya.GWidget;
    public failBox!: Laya.GWidget;
    public imgClose!: Laya.GImage;
    public lbFail!: Laya.GTextField;
    public lbClose!: Laya.GTextField;
    public topBox!: Laya.GWidget;
    public lbTitle!: Laya.GTextField;
    public btnDetail!: ButtonBase;
    public btnClose!: Laya.GButton;
    public Item_FireTrial_Head!: Item_FireTrial_Head;
    public lbReward!: Laya.GTextField;
    public lbRewardCnt!: Laya.GTextField;
}

