/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/fireTrial/Vw_FireTrial_Match.lh
 */
export class Runtime_Vw_FireTrial_MatchBase extends Laya.GWidget {
    public imgTitle!: Laya.GImage;
    public imgJl!: Laya.GImage;
    public matchCom!: Laya.GWidget;
    public lbDes!: Laya.GTextField;
    public lbSum!: Laya.GTextField;
    public headCom!: Laya.GWidget;
    public lbClose!: Laya.GTextField;
}

