/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/fireTrial/Vw_FireTrial_Guide.lh
 */
export class Runtime_Vw_FireTrial_GuideBase extends Laya.GWidget {
    public imgClose!: Laya.GImage;
    public box1!: Laya.GWidget;
    public imgGuide1!: Laya.GImage;
    public box2!: Laya.GWidget;
    public imgGuide2!: Laya.GImage;
    public box3!: Laya.GWidget;
    public imgGuide3!: Laya.GImage;
    public box4!: Laya.GWidget;
    public imgTitle!: Laya.GImage;
    public pos1!: Laya.GImage;
    public pos2!: Laya.GImage;
    public pos3!: Laya.GImage;
    public pos4!: Laya.GImage;
    public pos5!: Laya.GWidget;
    public imgGuide4!: Laya.GImage;
    public lbDes!: Laya.GTextField;
    public lbClose!: Laya.GTextField;
}

