/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Item_FireTrial_Head } from "./Item_FireTrial_Head";

/**
 * resources/ui/prefab/fireTrial/Vw_fireTrial_Win.lh
 */
export class Runtime_Vw_fireTrial_WinBase extends Laya.GWidget {
    public imgTitle!: Laya.GImage;
    public box!: Laya.GWidget;
    public gold!: Laya.GWidget;
    public lbCnt!: Laya.GTextField;
    public img!: Laya.GImage;
    public list!: Laya.GList;
    public lbDes1!: Laya.GTextField;
    public lbDes2!: Laya.GTextField;
    public lbDes3!: Laya.GTextField;
    public lbClose!: Laya.GTextField;
    public Item_FireTrial_Head_1!: Item_FireTrial_Head;
}

