/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/fireTrial/Vw_FireTrial_Enter.lh
 */
export class Runtime_Vw_FireTrial_EnterBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public lbTitle!: Laya.GTextField;
    public lbDes!: Laya.GTextField;
    public btnClose!: ButtonBase;
    public btnStart!: ButtonBase;
    public cdCom!: Laya.GWidget;
    public lbTime!: Laya.GTextField;
}

