/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/main/comp/Item_AdCard.lh
 */
export class Runtime_Item_AdCardBase extends Laya.GButton {
    public bgText!: Laya.GImage;
    public lb!: Laya.GTextField;
}

