/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/main/comp/Item_Arena.lh
 */
export class Runtime_Item_ArenaBase extends Laya.GButton {
    public imgBgMulti!: Laya.GImage;
    public lbMulti!: Laya.GTextField;
    public bgText!: Laya.GImage;
    public imgLock!: Laya.GImage;
    public lb!: Laya.GTextField;
}

