/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/main/comp/Item_FireTrial.lh
 */
export class Runtime_Item_FireTrialBase extends Laya.GButton {
    public bgText!: Laya.GImage;
    public imgLock!: Laya.GImage;
    public lb!: Laya.GTextField;
}

