/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/main/comp/Item_WarOrder.lh
 */
export class Runtime_Item_WarOrderBase extends Laya.GButton {
    public imgProBg!: Laya.GImage;
    public imgPro!: Laya.GImage;
    public bgText!: Laya.GImage;
    public imgLock!: Laya.GImage;
    public proBar!: Laya.GProgressBar;
    public lb!: Laya.GTextField;
}

