/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../../Component/ButtonBase";
        
/**
 * resources/ui/prefab/main/comp/Btn_BuyStamina.lh
 */
export class Runtime_Btn_BuyStaminaBase extends ButtonBase {
    public lbNeed!: Laya.GTextField;
}
        
