/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/scene/Vw_SceneLoading.lh
 */
export class Runtime_Vw_SceneLoadingBase extends Laya.GWidget {
    public bg!: Laya.GImage;
    public black!: Laya.GImage;
}

