/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/warOrder/Vw_WarOrderBuyTip.lh
 */
export class Runtime_Vw_WarOrderBuyTipBase extends Laya.GWidget {
    public btnBuy!: Laya.GButton;
    public imgAd!: Laya.GImage;
    public txtBtnBuy!: Laya.GTextField;
    public btnClose!: Laya.GButton;
    public txtTitle!: Laya.GTextField;
    public txtTime!: Laya.GTextField;
    public txt1!: Laya.GTextField;
    public txt2!: Laya.GTextField;
    public txt3!: Laya.GTextField;
    public txt4!: Laya.GTextField;
    public txt5!: Laya.GTextField;
}

