/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/warOrder/Vw_WarOrderGuideTip.lh
 */
export class Runtime_Vw_WarOrderGuideTipBase extends Laya.GWidget {
    public imgTitle!: Laya.GImage;
    public iconHelp1!: Laya.GImage;
    public imgJt1!: Laya.GImage;
    public iconHelp2!: Laya.GImage;
    public iconHelp3!: Laya.GImage;
    public imgJt2!: Laya.GImage;
    public iconHelp4!: Laya.GImage;
    public txtTip!: Laya.GTextField;
    public txt1!: Laya.GTextField;
    public txt2!: Laya.GTextField;
    public txt3!: Laya.GTextField;
    public txt4!: Laya.GTextField;
}

