/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { ButtonBase } from "../Component/ButtonBase";

/**
 * resources/ui/prefab/warOrder/Vw_WarOrder.lh
 */
export class Runtime_Vw_WarOrderBase extends Laya.GWidget {
    public list!: Laya.GList;
    public imgGold!: Laya.GImage;
    public iconGold!: Laya.GImage;
    public lbGold!: Laya.GTextField;
    public btnAdd!: ButtonBase;
    public progressPanel!: Laya.GPanel;
    public imgListPro!: Laya.GImage;
    public btnClose!: Laya.GButton;
    public btnAct!: Laya.GButton;
    public imgAct!: Laya.GImage;
    public comProg!: Laya.GButton;
    public btnHelp!: Laya.GButton;
    public txtTime!: Laya.GTextField;
    public txt1!: Laya.GTextField;
    public txt2!: Laya.GTextField;
    public txtTitle!: Laya.GTextField;
}

