/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/warOrder/Item_WarOrder2.lh
 */
export class Item_WarOrder2Base extends Laya.GWidget {
    public imgSuo!: Laya.GImage;
    public proBar!: Laya.GProgressBar;
    public txtTitle!: Laya.GTextField;
    public txtDesc!: Laya.GTextField;
    public btnFetch!: Laya.GButton;
}

