/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/warOrder/Item_WarOrder1.lh
 */
export class Item_WarOrder1Base extends Laya.GWidget {
    public imgCur!: Laya.GImage;
    public imgPro1!: Laya.GImage;
    public imgPro2!: Laya.GImage;
    public img1!: Laya.GImage;
    public imgStar!: Laya.GImage;
    public item1!: Laya.GButton;
    public icon1!: Laya.GWidget;
    public imgGet1!: Laya.GImage;
    public btnFetch1!: Laya.GButton;
    public item2!: Laya.GButton;
    public icon2!: Laya.GWidget;
    public imgGet2!: Laya.GImage;
    public imgLock!: Laya.GImage;
    public btnFetch2!: Laya.GButton;
    public txtLv!: Laya.GTextField;
}

