/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/scene/PlayerHalo.lh
 */
export class Runtime_PlayerHaloBase extends Laya.GWidget {
    public halo!: Laya.GWidget;
    public pb!: Laya.GProgressBar;
}

