/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/ui/prefab/scene/BuildingHp.lh
 */
export class Runtime_BuildingHpBase extends Laya.GWidget {
    public pb!: Laya.GProgressBar;
    public hpBar!: Laya.GImage;
}

